sonar.projectKey=faizansb_cohort-9-mern-13815-muhammad
sonar.organization=faizansb

sonar.sources=Backend/src,Frontend/src
sonar.tests=Backend/tests,Frontend/src
sonar.test.inclusions=**/*.test.js,**/*.test.jsx
sonar.exclusions=**/node_modules/**,**/dist/**